config/routes.rb
RedmineApp::Application.routes.draw do
  resources :projects do
    resources :tid_bits do
      resources :tidbit_comments, only: [:create]
    end
    resources :tid_bit_tags, except: [:show]
  end

  match 'projects/:id/settings/tid_bit_tags', to: 'tid_bit_tags#index', via: [:get, :post], as: 'project_settings_tid_bit_tags'
end

app/models/tid_bit.rb
class TidBit < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
  belongs_to :tid_bit_tag, optional: true
  has_many :tid_bit_attachments, dependent: :destroy
  has_many :tidbit_comments, dependent: :destroy

  acts_as_taggable_on :tags

  validates :subject, presence: true
  validates :body, presence: true

  accepts_nested_attributes_for :tid_bit_attachments, allow_destroy: true

  def body_html
    bbcode_to_html(body).gsub("\n", "<br>").html_safe
  end

  private

  def bbcode_to_html(text)
    require 'bb-ruby'
    BBRuby.to_html(body).gsub("\n", "<br>").html_safe
  end
end

app/models/tid_bit_attachment.rb
class TidBitAttachment < ActiveRecord::Base
  belongs_to :tid_bit

  validates :file_name, presence: true
  validates :file_path, presence: true
end

app/models/tid_bit_tag.rb
class TidBitTag < ActiveRecord::Base
  has_many :tid_bits

  validates :name, presence: true
  validates :color, presence: true
end

app/models/tidbit_comment.rb
class TidbitComment < ActiveRecord::Base
  belongs_to :tid_bit
  belongs_to :user

  validates :content, presence: true
end

app/controllers/tid_bit_tags_controller.rb
class TidBitTagsController < ApplicationController
  before_action :find_project
  before_action :authorize

  def index
    @tags = TidBitTag.all
  end

  def new
    @tag = TidBitTag.new
  end

  def create
    @tag = TidBitTag.new(tag_params)
    if @tag.save
      flash[:notice] = l(:notice_successful_create)
      redirect_to project_settings_tid_bit_tags_path(@project)
    else
      render :new
    end
  end

  def edit
    @tag = TidBitTag.find(params[:id])
  end

  def update
    @tag = TidBitTag.find(params[:id])
    if @tag.update(tag_params)
      flash[:notice] = l(:notice_successful_update)
      redirect_to project_settings_tid_bit_tags_path(@project)
    else
      render :edit
    end
  end

  def destroy
    @tag = TidBitTag.find(params[:id])
    @tag.destroy
    flash[:notice] = l(:notice_successful_delete)
    redirect_to project_settings_tid_bit_tags_path(@project)
  end

  private

  def find_project
    @project = Project.find(params[:project_id])
  end

  def tag_params
    params.require(:tid_bit_tag).permit(:name, :color)
  end
end

app/controllers/tid_bits_controller.rb
class TidBitsController < ApplicationController
  before_action :find_project
  before_action :authorize
  before_action :find_tid_bit, only: [:show, :edit, :update, :destroy]

  helper :sort
  include SortHelper

  def index
    sort_init 'id', 'desc'
    sort_update 'id' => "#{TidBit.table_name}.id",
                'subject' => "#{TidBit.table_name}.subject",
                'created_at' => "#{TidBit.table_name}.created_at",
                'user' => "#{User.table_name}.firstname"

    @tid_bits = @project.tid_bits.joins(:user).order(sort_clause)
    if params[:search].present?
      @tid_bits = @tid_bits.where("subject LIKE ?", "%#{params[:search]}%")
    end
    if params[:tag].present?
      @tid_bits = @tid_bits.joins(:tid_bit_tag).where(tid_bit_tags: { name: params[:tag] })
    end
    @tid_bits = @tid_bits.paginate(page: params[:page], per_page: 10)
  end

  def show
    @comment = TidbitComment.new
  end

  def new
    @tid_bit = TidBit.new
    @tid_bit.tid_bit_attachments.build
  end

  def create
    @tid_bit = TidBit.new(tid_bit_params)
    @tid_bit.project = @project
    @tid_bit.user = User.current
    if @tid_bit.save
      save_attachments
      redirect_to project_tid_bits_path(@project), notice: 'Tid-Bit was successfully created.'
    else
      render :new
    end
  end

  def edit
    @tid_bit.tid_bit_attachments.build if @tid_bit.tid_bit_attachments.empty?
  end

  def update
    @tid_bit.assign_attributes(tid_bit_params)
    if @tid_bit.save
      save_attachments
      redirect_to project_tid_bit_path(@project, @tid_bit), notice: 'Tid-Bit was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @tid_bit.destroy
    redirect_to project_tid_bits_path(@project), notice: 'Tid-Bit was successfully deleted.'
  end

  def create_comment
    @tid_bit = TidBit.find(params[:tid_bit_id])
    @comment = @tid_bit.tidbit_comments.build(comment_params)
    @comment.user = User.current

    if @comment.save
      redirect_to project_tid_bit_path(@project, @tid_bit), notice: 'Comment was successfully added.'
    else
      render :show
    end
  end

  private

  def find_project
    @project = Project.find(params[:project_id])
  end

  def find_tid_bit
    @tid_bit = TidBit.find(params[:id])
  end

  def tid_bit_params
    params.require(:tid_bit).permit(:subject, :body, :tid_bit_tag_id, tid_bit_attachments_attributes: [:id, :file_name, :file_path, :_destroy])
  end

  def comment_params
    params.require(:tidbit_comment).permit(:content)
  end

  def save_attachments
    if params[:tid_bit][:attachments]
      params[:tid_bit][:attachments].each do |attachment|
        next if attachment.blank? || !attachment.respond_to?(:original_filename)

        TidBitAttachment.create(
          tid_bit: @tid_bit,
          file_name: attachment.original_filename,
          file_path: save_file(attachment)
        )
      end
    end
  end

  def save_file(file)
    directory = "public/uploads"
    path = File.join(directory, file.original_filename)
    File.open(path, "wb") { |f| f.write(file.read) }
    path
  end
end

app/controllers/tidbit_comments_controller.rb
class TidbitCommentsController < ApplicationController
  before_action :find_project
  before_action :find_tid_bit

  def create
    @comment = @tid_bit.tidbit_comments.build(comment_params)
    @comment.user = User.current
    if @comment.save
      redirect_to project_tid_bit_path(@project, @tid_bit), notice: 'Comment added.'
    else
      render 'tid_bits/show'
    end
  end

  private

  def find_project
    @project = Project.find(params[:project_id])
  end

  def find_tid_bit
    @tid_bit = TidBit.find(params[:tid_bit_id])
  end

  def comment_params
    params.require(:tidbit_comment).permit(:content)
  end
end

app/views/projects/settings/_tid_bit_tags.html.erb
<!-- plugins/tid_bits/app/views/projects/settings/_tid_bit_tags.html.erb -->
<% if User.current.allowed_to?(:manage_tid_bit_tags, @project) %>
  <%= link_to l(:label_tid_bit_tag_new), new_project_tid_bit_tag_path(@project), class: 'icon icon-add' %>

  <table class="list">
    <thead>
      <tr>
        <th><%= l(:field_name) %></th>
        <th><%= l(:field_color) %></th>
        <th><%= l(:label_actions) %></th>
      </tr>
    </thead>
    <tbody>
      <% @project.tid_bit_tags.each do |tag| %>
        <tr>
          <td><%= tag.name %></td>
          <td><span style="color:<%= tag.color %>;"><%= tag.color %></span></td>
          <td>
            <%= link_to l(:button_edit), edit_project_tid_bit_tag_path(@project, tag), class: 'icon icon-edit' %>
            <%= link_to l(:button_delete), project_tid_bit_tag_path(@project, tag), method: :delete, data: { confirm: l(:text_are_you_sure) }, class: 'icon icon-del' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/projects/settings/_tid_bits.html.erb
<!-- app/views/projects/settings/_tid_bits.html.erb -->
<p>Configure Tid-Bits settings here.</p>

app/views/tid_bit_tags/_form.html.erb
<%= form_with(model: [@project, @tag], local: true) do |f| %>
  <div class="box tabular">
    <p>
      <%= f.label :name, l(:field_name) %><br>
      <%= f.text_field :name %>
    </p>
    <p>
      <%= f.label :color, l(:field_color) %><br>
      <%= f.select :color, options_for_select([
          ['Red', '#FF0000'],
          ['Green', '#008000'],
          ['Blue', '#0000FF'],
          ['Yellow', '#FFFF00'],
          ['Purple', '#800080'],
          ['Orange', '#FFA500'],
          ['Black', '#000000'],
          ['White', '#FFFFFF']
        ], @tag.color), { prompt: 'Select Color' }, { class: 'color-dropdown' } %>
    </p>
    <p>
      <%= f.submit l(:button_save) %>
    </p>
  </div>
<% end %>

app/views/tid_bit_tags/edit.html.erb
<h2>Edit Tag</h2>

<%= render 'form' %>

<%= link_to 'Back', project_tid_bit_tags_path(@project) %>

app/views/tid_bit_tags/index.html.erb
<h2><%= l(:label_tid_bit_tags) %></h2>

<%= link_to l(:label_tid_bit_tag_new), new_project_tid_bit_tag_path(@project), class: 'icon icon-add' %>

<table class="list">
  <thead>
    <tr>
      <th><%= l(:field_name) %></th>
      <th><%= l(:field_color) %></th>
      <th><%= l(:label_actions) %></th>
    </tr>
  </thead>
  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.name %></td>
        <td><span style="color:<%= tag.color %>;"><%= tag.color %></span></td>
        <td>
          <%= link_to l(:button_edit), edit_project_tid_bit_tag_path(@project, tag), class: 'icon icon-edit' %>
          <%= link_to l(:button_delete), project_tid_bit_tag_path(@project, tag), method: :delete, data: { confirm: l(:text_are_you_sure) }, class: 'icon icon-del' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tid_bit_tags/new.html.erb
<h2>New Tag</h2>

<%= render 'form' %>

<%= link_to 'Back', project_tid_bit_tags_path(@project) %>

app/views/tid_bits/_form.html.erb
<%= stylesheet_link_tag 'tid_bits', plugin: 'tid_bits' %>
<%= javascript_include_tag 'tid_bits', plugin: 'tid_bits' %>
<%= form_with(model: [@project, @tid_bit], local: true) do |f| %>
  <% if @tid_bit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tid_bit.errors.count, "error") %> prohibited this tid_bit from being saved:</h2>

      <ul>
        <% @tid_bit.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tag %><br>
    <%= f.collection_select :tid_bit_tag_id, TidBitTag.all, :id, :name, include_blank: true %>
  </div>

  <div class="field">
    <%= f.label :subject %><br>
    <%= f.text_field :subject, size: 60 %>
  </div>

  <div class="field">
    <%= f.label :body %><br>
    <div id="tabs">
      <div id="editor-tab" class="selected">Editor</div>
      <div id="preview-tab">Preview</div>
    </div>
    <div id="editor-content">
      <div class="bbcode-toolbar"></div>
      <%= f.text_area :body, rows: 20, cols: 80 %>
    </div>
    <div id="preview-content" style="display: none;"></div>
  </div>

  <div class="field">
    <%= f.label :attachments %><br>
    <%= file_field_tag 'tid_bit[attachments][]', multiple: true %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tid_bits/edit.html.erb
<h2><%= l(:tid_bit_edit) %></h2>

<%= render 'form' %>

<%= link_to 'Back', project_tid_bits_path(@project) %>

app/views/tid_bits/index.html.erb
<% content_for :header_tags do %>
  <%= stylesheet_link_tag 'tid_bits', :plugin => 'tid_bits' %>
<% end %>

<div id="content">
  <div class="contextual">
    <%= link_to l(:label_tid_bit_new), new_project_tid_bit_path(@project), class: 'icon icon-add new-issue' %>
  </div>

  <h2>Tid-Bits</h2>

  <div class="issue-search">
    <%= form_tag project_tid_bits_path(@project), method: :get do %>
      <div class="row">
        <div class="small-10 columns">
          <%= text_field_tag :search, params[:search], placeholder: "Search...", class: "small" %>
          <%= select_tag :tag, options_for_select(@project.tid_bits.joins(:tid_bit_tag).distinct.pluck('tid_bit_tags.name'), params[:tag]), prompt: "Select Tag", class: "small" %>
          <%= select_tag :sort, options_for_select([['ID', 'id'], ['Subject', 'subject'], ['Created At', 'created_at']], params[:sort]), prompt: "Sort By", class: "small" %>
        </div>
        <div class="small-2 columns">
          <%= submit_tag "Search", class: "small button" %>
        </div>
      </div>
    <% end %>
  </div>

  <table class="list issues">
    <thead>
      <tr>
        <th><%= sort_link @query, 'id', caption: "#" %></th>
        <th><%= sort_link @query, 'subject', caption: "Subject" %></th>
        <th><%= sort_link @query, 'user', caption: "Submitted By" %></th>
        <th><%= sort_link @query, 'created_at', caption: "Created At" %></th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @tid_bits.each do |tid_bit| %>
        <tr>
          <td><%= tid_bit.id %></td>
          <td>
            <% if tid_bit.tid_bit_tag.present? %>
              <span style="color: <%= tid_bit.tid_bit_tag.color %>;">[<%= tid_bit.tid_bit_tag.name %>]</span>
            <% end %>
            <%= link_to tid_bit.subject, project_tid_bit_path(@project, tid_bit) %>
          </td>
          <td><%= tid_bit.user %></td>
          <td><%= tid_bit.created_at %></td>
          <td>
            <% if User.current.admin? || User.current == tid_bit.user %>
              <%= link_to 'Edit', edit_project_tid_bit_path(@project, tid_bit) %> |
              <%= link_to 'Delete', project_tid_bit_path(@project, tid_bit), method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="pagination">
    <%= will_paginate @tid_bits %>
  </div>
</div>

app/views/tid_bits/new.html.erb
<h2><%= l(:tid_bit_new) %></h2>

<%= render 'form' %>

<%= link_to 'Back', project_tid_bits_path(@project) %>

app/views/tid_bits/show.html.erb
<h2>
  <% if @tid_bit.tid_bit_tag.present? %>
    <span style="color: <%= @tid_bit.tid_bit_tag.color %>;"><%= @tid_bit.tid_bit_tag.name %></span> -
  <% end %>
  <%= @tid_bit.subject %>
</h2>

<div class="tid-bit-body">
  <%= @tid_bit.body_html.html_safe %>
</div>

<div class="attachments">
  <h3>Attachments</h3>
  <% @tid_bit.tid_bit_attachments.each do |attachment| %>
    <p><%= link_to attachment.file_name, attachment.file_path %></p>
  <% end %>
</div>

<div class="comments">
  <h3>Comments</h3>
  <% @tid_bit.tidbit_comments.each do |comment| %>
    <p><strong><%= comment.user %>:</strong> <%= comment.content %></p>
  <% end %>

  <%= form_with(model: [@project, @tid_bit, @comment], local: true) do |f| %>
    <p>
      <%= f.label :content %><br>
      <%= f.text_area :content %>
    </p>
    <p>
      <%= f.submit "Add Comment" %>
    </p>
  <% end %>
</div>

<%= link_to 'Back', project_tid_bits_path(@project) %>